name: actionlint
description: Static checker for GitHub Actions workflow files.
homepage: https://github.com/rhysd/actionlint
licenses:
  - MIT
languages:
  - YAML
filetypes:
  - ".github/workflows/*.yaml"
  - ".github/workflows/*.yml"
  - ".github/actions/**/*.yaml"
  - ".github/actions/**/*.yml"
categories:
  - Linter
source:
  id: pkg:github/rhysd/actionlint@v1.7.7
  asset:
    - target: darwin_arm64
      file: "actionlint_{{version}}_darwin_arm64.tar.gz"
      bin: actionlint
    - target: darwin_x64
      file: "actionlint_{{version}}_darwin_amd64.tar.gz"
      bin: actionlint
    - target: linux_x64
      file: "actionlint_{{version}}_linux_amd64.tar.gz"
      bin: actionlint
    - target: linux_arm64
      file: "actionlint_{{version}}_linux_arm64.tar.gz"
      bin: actionlint
bin:
  actionlint: "{{source.asset.bin}}"
