name: shellcheck
description: Static analysis tool for shell scripts
source: pkg:github/koalaman/shellcheck
version: "0.11.0"
filetypes:
  - "*.sh"
  - "*.bash"
  - "*.bats"
bin:
  shellcheck: shellcheck
platforms:
  linux/amd64:
    asset: shellcheck-v0.11.0.linux.x86_64.tar.gz
    binary: shellcheck-v0.11.0/shellcheck
  linux/arm64:
    asset: shellcheck-v0.11.0.linux.aarch64.tar.gz
    binary: shellcheck-v0.11.0/shellcheck
  darwin/amd64:
    asset: shellcheck-v0.11.0.darwin.x86_64.tar.gz
    binary: shellcheck-v0.11.0/shellcheck
  darwin/arm64:
    asset: shellcheck-v0.11.0.darwin.aarch64.tar.gz
    binary: shellcheck-v0.11.0/shellcheck
