name: shellcheck
description: Static analysis tool for shell scripts.
homepage: https://www.shellcheck.net/
licenses:
  - GPL-3.0-or-later
languages:
  - Bash
  - sh
filetypes:
  - "*.sh"
  - "*.bash"
categories:
  - Linter
source:
  id: pkg:github/koalaman/shellcheck@v0.10.0
  asset:
    - target: darwin_arm64
      file: "shellcheck-{{version}}.darwin.aarch64.tar.xz"
      bin: shellcheck
    - target: darwin_x64
      file: "shellcheck-{{version}}.darwin.x86_64.tar.xz"
      bin: shellcheck
    - target: linux_x64
      file: "shellcheck-{{version}}.linux.x86_64.tar.xz"
      bin: shellcheck
    - target: linux_arm64
      file: "shellcheck-{{version}}.linux.aarch64.tar.xz"
      bin: shellcheck
bin:
  shellcheck: "{{source.asset.bin}}"
